apiVersion: v1
kind: Secret
metadata:
  name: summit-worker-0-bmc-secret
type: Opaque
data:
  username: cm9vdA==
  password: aGVuZHJpeAo=

---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: summit-worker-0
spec:
  online: true
  bmc:
    address: ipmi://192.168.202.5
    credentialsName: summit-worker-0-bmc-secret
  bootMACAddress: 98:03:9B:61:C2:A9
